### ISSUE TITLE
"features.pyx" file issue

### ISSUE THREAD

**Issue by ShichenLiu** [piiswrong/dec#1]
When I extract features of STL10 dataset, I ran make_stl_data.py which use setup_features.py.
But I can't find the file "features.pyx" in it.

setup(
  name = "features",
  ext_modules = cythonize("features.pyx"),
  include_dirs = [np.get_include()]
)

and I got a
ValueError: 'features.pyx' doesn't match any files

So did I miss some steps and how can I fix it?
Thanks

**Comment by ShichenLiu** [comment]
I figured it out using features.pyx from somewhere else

**Comment by hkrds1996** [comment]
hi, I have the same problem.
Could you tell my how to deal with this problem?

**Comment by ShichenLiu** [comment]
checkout this https://github.com/cvondrick/pyvision/blob/master/vision/features.pyx

**Comment by hkrds1996** [comment]
@Lustralisk Thanks

**Comment by hkrds1996** [comment]
and do you know where is the hog? Features module has no attribute 'hog'.
I get a error in here.

> "H = np.asarray(Parallel(n_jobs=n_jobs)( delayed(features.hog)(X[i]) for i in xrange(N) ))"

**Comment by ShichenLiu** [comment]
@hukangrong It's been too long and I almost forgot about it, sorry. But you can try to refer to *stackoverflow*, I believe you can find your answer :)

**Comment by hkrds1996** [comment]
@Lustralisk I have one question. Whether you can do "python make_stl_data.py" successful?

**Comment by cvhci-plumcot** [comment]
Hi.
copy this files to dec folder.
https://github.com/cvondrick/pyvision/blob/master/vision/features.pyx

**add to dec.py**: from PIL import Image
 
**modify**: H = np.asarray(Parallel(n_jobs=n_jobs)( delayed(features.hog)(Image.fromarray(X[i])) for i in xrange(N) )) 

and **comment** this:

  # H_img = np.repeat(np.asarray([ hog_picture(H[i], 9) for i in xrange(100) ])[:, :,:,np.newaxis], 3, 3)
  # dispImg(H_img, 10, fname+'_hog.jpg')

**Comment by vivoutlaw** [comment]
Hi.
copy this file to dec folder.
https://github.com/cvondrick/pyvision/blob/master/vision/features.pyx

**add to dec.py**: from PIL import Image
 
**modify**: H = np.asarray(Parallel(n_jobs=n_jobs)( delayed(features.hog)(Image.fromarray(X[i])) for i in xrange(N) )) 

**and comment this**: 

H_img = np.repeat(np.asarray([ hog_picture(H[i], 9) for i in xrange(100) ])[:, :,:,np.newaxis], 3, 3)
dispImg(H_img, 10, fname+'_hog.jpg') 

You're good to go with this :)
