### ISSUE TITLE
about the caffe layer

### ISSUE THREAD

**Issue by gray0302** [piiswrong/dec#2]
When I run the code that you gave, I met some errors like data layer doesn't have the field seek and doesn't have the MULTI_T_LOSS type. Can you give me some advice how I solve these?

**Comment by piiswrong** [comment]
you need to use the caffe included in this repo, not your own caffe

**Comment by gray0302** [comment]
thanks, I just notice it.

**Comment by junwang929** [comment]
So what's the difference between your custom version caffe and the official caffe?  where do you edit the files? such as MULTI_T_LOSS?
