### ISSUE TITLE
Leveldb already held by process

### ISSUE THREAD

**Issue by jeronimok** [piiswrong/dec#7]
Hello,
when running 'python dec.py mnist' I'm getting this problem:

Traceback (most recent call last):
  File "dec.py", line 768, in <module>
    DisKmeans(db, lam)
  File "dec.py", line 721, in DisKmeans
    write_db(weight, np.zeros((weight.shape[0],)), 'train_weight')
  File "dec.py", line 552, in write_db
    db = leveldb.LevelDB(fname)
leveldb.LevelDBError: IO error: lock train_weight/LOCK: already held by process

Regards

**Comment by bfolkens** [comment]
Try upgrading leveldb.  I had 0.1 installed and there seems to be a problem closing the db.  Running:

```
pip install -U leveldb
```

Fixed it for me.  The current version is 0.194 and it seems to be working now.

**Comment by jeronimok** [comment]
It worked!
Thanks! :)
