### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by hkrds1996** [piiswrong/dec#8]
How to fix this problem?
When I do "python make_stl_data1.py", I got a errors. The error is:

> root@hu-N551JW:/home/hu/dec-master/dec# python make_stl_data1.py
> Building HOG feature extractor...
> running build
> running install
> running build
> running install_egg_info
> Writing /usr/local/lib/python2.7/dist-packages/features-0.0.0.egg-info
> Preparing stl data. This could take a while...
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/usr/lib/python2.7/multiprocessing/pool.py", line 325, in _handle_workers
>     while thread._state == RUN or (pool._cache and thread._state != TERMINATE):
> AttributeError: '_MainThread' object has no attribute '_state'

**Comment by bhavikajalli** [comment]
How did you fix this issue?

**Comment by hkrds1996** [comment]
@bhavikajalli I took some time to fix it, but I have deleted my dec.py. So, totally sorry to response you. I remember it's the hog shape not work.

**Comment by hkrds1996** [comment]
@bhavikajalli it's senseless to waste time to fix the problem. Just keep you time to understand how the code running, if other datasets can work. Because the code of author is kind of mess.
